quiet_launch: false
debug_logging: true
games:
  bf2:
    executable_name: BF2.playbf2.exe
    executable_path: bin
    install_path: C:\Games\Battlefield 2
    args: [ "+fullscreen", "0", "+szx", "1600", "+szy", "900" ]
    hooks:
      - handler: set-default-profile
        when: pre-launch
        args:
          profile: "0010"
      - handler: purge-server-history
        when: pre-launch
      - handler: purge-shader-cache
        when: pre-launch
      - handler: purge-logo-cache
        when: pre-launch