// Code generated by MockGen. DO NOT EDIT.
// Source: software_finder.go
//
// Generated by this command:
//
//	mockgen -source=software_finder.go -destination=software_finder_mock_test.go -package=software_finder -write_package_comment=false
package software_finder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	registry "golang.org/x/sys/windows/registry"
)

// MockRegistryRepository is a mock of RegistryRepository interface.
type MockRegistryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryRepositoryMockRecorder
}

// MockRegistryRepositoryMockRecorder is the mock recorder for MockRegistryRepository.
type MockRegistryRepositoryMockRecorder struct {
	mock *MockRegistryRepository
}

// NewMockRegistryRepository creates a new mock instance.
func NewMockRegistryRepository(ctrl *gomock.Controller) *MockRegistryRepository {
	mock := &MockRegistryRepository{ctrl: ctrl}
	mock.recorder = &MockRegistryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryRepository) EXPECT() *MockRegistryRepositoryMockRecorder {
	return m.recorder
}

// GetStringValue mocks base method.
func (m *MockRegistryRepository) GetStringValue(k registry.Key, path, valueName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStringValue", k, path, valueName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStringValue indicates an expected call of GetStringValue.
func (mr *MockRegistryRepositoryMockRecorder) GetStringValue(k, path, valueName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringValue", reflect.TypeOf((*MockRegistryRepository)(nil).GetStringValue), k, path, valueName)
}

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// DirExists mocks base method.
func (m *MockFileRepository) DirExists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirExists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirExists indicates an expected call of DirExists.
func (mr *MockFileRepositoryMockRecorder) DirExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirExists", reflect.TypeOf((*MockFileRepository)(nil).DirExists), path)
}

// FileExists mocks base method.
func (m *MockFileRepository) FileExists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockFileRepositoryMockRecorder) FileExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockFileRepository)(nil).FileExists), path)
}
